name: It's Linda Julia
description: Startups, movie reviews, romance and life
meta_description: "ItsLindaJulia - Startups, movie reviews, romance and life"

aboutPage: true

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
paginate: 10
baseurl: /
domain_name: 'http://www.itslindajulia.com/'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://www.itslindajulia.com/'
author:         'Linda Julia'
authorTwitter:  'tbd'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
