name: It's Linda Julia
description: Posting weekly on Saturdays (maybe)
meta_description: "Hi, it's Linda Julia - posting weekly on Saturdays"

aboutPage: true

categories: writing

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
paginate: 10
baseurl: '/'
domain_name: 'https://www.itslindajulia.com/'
google_analytics: 'UA-90757858-1'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'https://www.itslindajulia.com/'
author:         'Linda Julia'
authorInsta:    'itslindajulia'

permalink:       /404.html

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
